apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: controller-manager
  labels:
    app: controller-manager
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - dev/chrishartley/github-runner
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: controller-manager-private-key
  labels:
    app: controller-manager
secretDescriptor:
  backendType: secretsManager
  data:
    - key: dev/chrishartley/github-runner-app-key
      name: github_app_private_key
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: controller-manager-token
  labels:
    app: controller-manager
secretDescriptor:
  backendType: secretsManager
  data:
    - key: dev/chrishartley/github-runner
      name: github_token
      property: token # make sure name and property match!
